# Use root/example user/password credentials
version: '3.1'

services:
  mysql:
    container_name: "menvi-mysql"
    ports:
      - "3307:3306"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    volumes:
      - mysqlvolume:/var/lib/mysql
volumes:
  mysqlvolume:
    driver: local
